import { AydinlatmaMetni } from "@/components/aydinlatma-metni"

export const metadata = {
  title: "Ticari Elektronik İleti Aydınlatma Metni | FW İlaç",
  description: "6698 Sayılı Kişisel Verilerin Korunması Kanunu kapsamında aydınlatma metni",
}

const content = [
  "TİCARİ ELEKTRONİK İLETİ GÖNDERİLMESİNE İLİŞKİN TOPLANAN LİŞİSEL VERİLER İLE İLGİLİ AYDINLATMA METNİ",
  "​",
  "Burada yer alan açıklamalar 6698 sayılı Kişisel Verilerin Korunması Kanunu (“KVK Kanunu”) ve ilgili mevzuat uyarınca, VERİ SORUMLUSU sıfatıyla, FW İlaç A. Ş. (“Şirket”) nezdinde toplanan kişisel verilerin işlenmesine ilişkin bilgilendirmeleri içermektedir.",
  "İşbu aydınlatma metni ile; kişisel verisi toplanan (“Veri Sahibi”) kişi gruplarına yönelik olarak; toplanan kişisel veriler, kişisel verilerin toplanma yöntemi, işlenme amaçları, hukuki sebepleri, işlenen kişisel verilerin kimlere ve hangi amaçlarla aktarılabileceği ve kişisel veri sahiplerinin hakları ile ilgili kişinin veri sorumlusuna başvuru yol ve yöntemleri konularında bilgilendirmek amaçlanmıştır.",
  "KVK Kanunu kapsamında kişisel veri, kimliği belirli veya belirlenebilir gerçek kişiye ilişkin her türlü bilgiyi (“Kişisel Veri”) ve özel nitelikli kişisel veri ise, ırk, etnik köken, siyasi düşünce, felsefi inanç, din, mezhep veya diğer inançlar, kılık ve kıyafet, dernek, vakıf ya da sendika üyeliği, sağlık, cinsel hayat, ceza mahkûmiyeti ve güvenlik tedbirleriyle ilgili verileri ile biyometrik ve genetik verileri (“Özel Nitelikli Kişisel Veri”) ifade eder. Veri Sorumlusu sıfatıyla, sizlerle olan iş ilişkimiz veya irtibatımız dâhilinde, Kişisel Verilerin; işlenmelerini gerektiren amaçlara uygun ve bu amaç ile bağlantılı, sınırlı ve ölçülü olmak üzere kaydedilecek, depolanabilecek, muhafaza edilebilecek, gereklilik durumlarında yeniden düzenlenecek, kanunen işbu Kişisel Verileri talep etmeye yetkili olan kurumlar ile paylaşılabilecek ve KVK Kanunu kapsamında sayılan sair şekillerde işlenebilecektir.",
  "KVK Kanunu’nda Kişisel Verilerin İşlenmesi; “Kişisel verilerin tamamen veya kısmen otomatik olan ya da herhangi bir veri kayıt sisteminin parçası olmak kaydıyla otomatik olmayan yollarla elde edilmesi, kaydedilmesi, depolanması, muhafaza edilmesi, değiştirilmesi, yeniden düzenlenmesi, açıklanması, aktarılması, devralınması, elde edilebilir hâle getirilmesi, sınıflandırılması ya da kullanılmasının engellenmesi gibi veriler üzerinde gerçekleştirilen her türlü işlem” olarak tanımlanmaktadır.",
  "İşbu aydınlatma metninde kişisel veriler ve özel nitelikli kişisel veriler beraber ‘’Kişisel veriler’’ olarak adlandırılabilecektir. Aydınlatma metninde yer alan amaçlar doğrultusunda işlenen kişisel verileriniz işbu metinde yer alan amaçlarla doğru orantılı olarak kişisel veriler işlenecek ve aktarım gerçekleştirilebilecektir.",
  "Toplanan Kişisel Veriler: Kimlik Verisi (Adı, Soyadı gibi), İletişim Verisi (E-posta adresi, telefon no gibi).",
  "Kişisel Verilerin İşlenme Amacı: Finans ve muhasebe ı̇şlerinin yürütülmesi, ı̇letişim faaliyetlerinin yürütülmesi, lojistik faaliyetlerinin yürütülmesi, mal / hizmet satış sonrası destek hizmetlerinin yürütülmesi, müşteri ı̇lişkileri yönetimi süreçlerinin yürütülmesi, müşteri memnuniyetine yönelik aktivitelerin yürütülmesi, mal / hizmet satış süreçlerinin yürütülmesi, pazarlama analiz çalışmalarının yürütülmesi, reklam / kampanya / promosyon süreçlerinin yürütülmesi, sözleşme süreçlerinin yürütülmesi, talep / şikayetlerin takibi, taşınır mal ve kaynakların güvenliğinin temini, ürün / hizmetlerin pazarlama süreçlerinin yürütülmesi, tedarik zinciri yönetimi süreçlerinin yürütülmesi, firma / ürün / hizmetlere bağlılık süreçlerinin yürütülmesi, hukuk ı̇şlerinin takibi ve yürütülmesi, ı̇ş süreçlerinin ı̇yileştirilmesine yönelik önerilerin alınması ve değerlendirilmesi amaçlarıyla işlenmekte ve aktarılmaktadır.",
  "Kişisel Verilerin Toplanma Yöntemi: Kişisel verileriniz her türlü otomatik olan/olmayan yöntemler ile (Şirkete ve Şirket ile bağlantılı kuruluşlara sözlü/yazılı verdiğiniz bilgilerden, mağazalar ve/veya bulundukları fiziki/dijital ortamları, mobil uygulamaları dahil olmak üzere internet sitelerini ziyaret ve içerik incelemelerinizden, sosyal medya ve reklam ağı işletmecilerine ait sitelerdeki üyelik ve işlem bilgilerinizden, Şirket ve yukarıda anılan kuruluşlar nezdindeki (fiziki ve dijital) üye/kullanıcı/müşteri işlemleri ile alışverişlere ve müşteri memnuniyetine dair ödeme, tahsilat, teslimat, şikayet-kampanya, anket işlemlerim ve bunların yasal mali belgeleri ile diğer belgeleri, ayrıca internet ve iletişim cihazlarının ve/veya mobil uygulamaların muhtelif ortamlarda ve yerde kullanımlarından oluşan/edinilen yazılı, sözlü, görsel ve teknik verilerden) toplanabilmektedir.",
  "Kişisel Verilerin Toplanmasına İlişkin Hukuk Dayanak: KVK Kanunu 5 inci maddesinin (1) fıkrasında yer alan “Kişisel veriler ilgili kişinin açık rızası olmaksızın işlenemez.” “(2) fıkrasında yer alan (c) “Bir sözleşmenin kurulması veya ifasıyla doğrudan doğruya ilgili olması kaydıyla, sözleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması.”, (ç) “Veri sorumlusunun hukuki yükümlülüğünü yerine getirebilmesi için zorunlu olması.”, (d) “İlgili kişinin kendisi tarafından alenileştirilmiş olması.”, (e) “Bir hakkın tesisi, kullanılması veya korunması için veri işlemenin zorunlu olması.”, (f) “İlgili kişinin temel hak ve özgürlüklerine zarar vermemek kaydıyla, veri sorumlusunun meşru menfaatleri için veri işlenmesinin zorunlu olması.’’ hâlinde, ilgili kişinin açık rızası aranmaksızın kişisel verilerinin işlenmesi mümkündür ve 6. Maddesinin 3 üncü fıkrasına göre, “Özel nitelikli kişisel verilerin işlenmesi yasaktır. Ancak bu verilerin işlenmesi; a) İlgili kişinin açık rızasının olması, b) Kanunlarda açıkça öngörülmesi, ç) İlgili kişinin alenileştirdiği kişisel verilere ilişkin ve alenileştirme iradesine uygun olması, d) Bir hakkın tesisi, kullanılması veya korunması için zorunlu olması, halinde mümkündür.” Kapsamında toplanmakta ve işlenmektedir.",
  "Kişisel Verilerin Aktarımı Hakkında: Kişisel verilerin aktarılması hususunu belirleyen kanunun; 8 inci maddesinin, 1 inci fıkrasına göre, ‘’Kişisel veriler, ilgili kişinin açık rızası olmaksızın aktarılamaz.’’ hükmüne göre, ve  2 inci fıkrasına göre, kişisel veriler; (a) bendi “5 inci maddenin ikinci fıkrasında,” (b) bendi “Yeterli önlemler alınmak kaydıyla,” 6 ncı maddenin üçüncü fıkrasında, “belirtilen şartlardan birinin bulunması hâlinde, ilgili kişinin açık rızası aranmaksızın aktarılabilir.’’ Hükmüne göre aktarım yapılacaktır.",
  "Kanun’un 8. ve 9. maddelerinde belirtilen şartlar çerçevesinde ve yukarıdaki maddede sayılan amaçlarla sınırlı kalmak koşuluyla aktarılır. Sayılanların dışında üçüncü kişilere herhangi bir kişisel veri aktarımı yapılmaz.",
  "Şirketimizle paylaşım ve aktarım yapılan kişisel verileriniz, doğrudan ya da dolaylı iştiraklerimizle, grup şirketleri, hissedar/ortaklarla, iş ortaklarımız, servis sağlayıcılarımız, tedarikçilerimiz ve belirleyeceğimiz (sosyal medya-online reklam ağı işletmecileri dahil) diğer işlenme amacının gerektirdiği üçüncü kişiler/kuruluşlar ile paylaşılabilecek ve aktarılabilecektir.",
  "KİŞİSEL VERİLERİN SAKLANMA SÜRESİ",
  "İşbu Aydınlatma Metninde anılan kanallar vasıtasıyla Şirketimiz ile paylaşılmış olunan kişisel veriler, 6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili mevzuatta süre öngörülmüş ise, öngörülen sürelere uygun şekilde saklanacaktır. KVK Kanunu kapsamında işbu amaçlar doğrultusunda kişisel verileriniz gerekli saklama süresi sonunda KVK Kanunu madde 7’nin usul ve esaslarına uygun olarak imha edilecektir. Kanun ve ilgili mevzuatta süre öngörülmüş ise anılan sürenin sona ermesi akabinde veya herhangi bir süre öngörülmemiş olması durumunda yapılacak işlemler Kişisel Verileri Saklama ve İmha Politikası’nda belirtilmiştir.",
  "İLGİLİ KİŞİNİN HAKLARI",
  "KVK Kanunu’nun ilgili kişinin haklarını düzenleyen 11. Maddesi gereğince; Şirkete başvurarak kendinizle ilgili,",
  "Kişisel veri işlenip işlenmediğini öğrenme, kişisel verileri işlenmişse buna ilişkin bilgi talep etme, kişisel verilerin işlenme amacını ve bunların amacına uygun kullanılıp kullanılmadığını öğrenme, yurt içinde veya yurt dışında kişisel verilerin aktarıldığı üçüncü kişileri bilme, kişisel verilerin eksik veya yanlış işlenmiş olması hâlinde bunların düzeltilmesini ve bu kapsamda yapılan işlemlerin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, 6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili diğer kanun hükümlerinde öngörülen şartlar çerçevesinde kişisel verilerin silinmesini veya yok edilmesini isteme ve bu kapsamda yapılan işlemlerin kişisel verilerin aktarıldığı üçüncü kişilere bildirilmesini isteme, işlenen verilerin münhasıran otomatik sistemler vasıtasıyla analiz edilmesi suretiyle kişinin kendisi aleyhine bir sonucun ortaya çıkmasına itiraz etme, kişisel verilerin kanuna aykırı olarak işlenmesi sebebiyle zarara uğraması hâlinde zararın giderilmesini talep etme haklarına  sahipsiniz.",
  "VERİ SORUMLUSUNA BAŞVURU YOLLARI",
  "Sahip olduğunuz haklarınızı kullanmak istemeniz halinde, başvurularınızı 10.03.2018 tarih ve 30356 sayılı Veri Sorumlusuna Başvuru Usul Ve Esasları Hakkında Tebliğ’de yer alan usul ve esaslarına uygun olarak kimliğinizi gösteren belgelerle birlikte; https://fw.com.tr/ adresinde bulunan Başvuru Formu doldurulduktan sonra ıslak imzalı bir nüshasının;",
  "Bizzat elden veya noter aracılığı ile “FW İlaç A. Ş. Nisbetiye Mah. Nisbetiye Cad. Özden İş Merkezi No:22 Kat:3 Beşiktaş / İSTANBUL” adresine iletilmesi,",
  "Kayıtlı elektronik posta (KEP) adresi, güvenli elektronik imza, mobil imza ya da Şirketimize daha önce bildirdiğiniz ve sistemlerimizde kayıtlı bulunan elektronik posta adresini kullanmak suretiyle soft ortamda info@fw.com.tr adresine elektronik posta ile gönderilmesi,",
  "KVK Kanunu’nda belirtilen diğer yöntemlerle başvurarak iletebilirsiniz.",
  "Kişisel veri sahipleri adına üçüncü kişilerin başvuru talebinde bulunabilmesi için veri sahibi tarafından başvuruda bulunacak kişi adına noter kanalıyla düzenlenmiş özel vekâletname bulunmalıdır.",
  "Başvurunuzda yer alan talep veya talepleriniz, niteliğine göre en kısa sürede ve en geç 30 (otuz) gün içinde ücretsiz olarak sonuçlandırılacaktır. Ancak, işlemin Şirket için ayrıca bir maliyeti gerektirmesi hâlinde, Kişisel Verileri Koruma Kurulu tarafından belirlenen tarifedeki ücret alınacaktır."
]

export default function TicariElektronikAydinlatmaPage() {
  return (
    <AydinlatmaMetni
      title="Ticari Elektronik İleti Aydınlatma Metni"
      content={content}
    />
  )
}